### ISSUE TITLE
No database specified, how it works doesn't explained

### ISSUE THREAD

**Issue by dims12** [spring-guides/gs-accessing-data-jpa#19]
It is said, that example will work with in-memory database, but where it set it was not said.

**Comment by mp911de** [comment]
That's a Spring Boot feature: [Embedded Database Support](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-sql.html#boot-features-embedded-database-support). H2 is bootstrapped as in-memory database by just having H2 on the class path.
