### ISSUE TITLE
spring-boot-gradle-plugin:2.0.5.RELEASE problem with JDK 11

### ISSUE THREAD

**Issue by milanjosipovic** [spring-guides/gs-accessing-data-jpa#37]
Hi
Problem: spring-boot-gradle-plugin:2.0.5.RELEASE won't work with JDK 11.
Error: Process 'command 'C:\Program Files\Java\jdk-11.0.1\bin\java.exe'' finished with non-zero exit value 1
Solution: After setting to 2.1.2.RELEASE it works fine.

**Comment by ETLJ** [comment]
> Hi
> Problem: spring-boot-gradle-plugin:2.0.5.RELEASE won't work with JDK 11.
> Error: Process 'command 'C:\Program Files\Java\jdk-11.0.1\bin\java.exe'' finished with non-zero exit value 1
> Solution: After setting to 2.1.2.RELEASE it works fine.

Thanks -- the same thing was happening to me as well and 2.1.2.RELEASE worked for me.

**Comment by Buzzardo** [comment]
This issue has been superseded by Spring Boot 3 and Java 17.
