### ISSUE TITLE
Unresolved directive in <stdin>

### ISSUE THREAD

**Issue by jo2** [spring-guides/gs-accessing-data-jpa#47]
In the getting started guide the code examples can't be found (see image).

![image](https://user-images.githubusercontent.com/7516893/65040366-7f6f6d80-d954-11e9-94f3-d746fbb05a46.png)

**Comment by peter-mueller** [comment]
Hallo! @gregturn Wäre toll wenn ihr das behoben kriegt. Viele Azubis hier wollen gerade mit diesem Tutorial lernen.

**Comment by Buzzardo** [comment]
Fixed in subsequent commits.
