### ISSUE TITLE
Additional H2 configuration info.

### ISSUE THREAD

**Issue by tiho2** [spring-guides/gs-accessing-data-jpa#51]
Does h2 has implicit configuration? I didn't found h2 user/password and any other configuration in example?
It would be useful to add following (later found) explanation from spring boot [docs](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-embedded-database-support):  

> Spring Boot can auto-configure embedded H2, HSQL, and Derby databases. You need not provide any connection URLs. You need only include a build dependency to the embedded database that you want to use.

**Comment by Buzzardo** [comment]
The guides use the default values, so no configuration is needed.
