### ISSUE TITLE
Typo in Accessing Data JPA guide

### ISSUE THREAD

**Issue by SinghCoder** [spring-guides/gs-accessing-data-jpa#52]
Hello!

There is a typo in the [guide](https://spring.io/guides/gs/accessing-data-jpa/) Getting Started | Accessing Data with JPA.
After the code for AccessingDataJpaApplication.java, you mentioned that it calls `findOne()` to fetch a single `Customer` by its ID., but it should be `findById()` instead.

![findOneById](https://user-images.githubusercontent.com/32142363/81639185-de7c7800-9438-11ea-8b5d-68b808d7bbf2.png)

**Comment by Buzzardo** [comment]
Fixed.
