### ISSUE TITLE
Document text repeated

### ISSUE THREAD

**Issue by maxyou** [spring-guides/gs-accessing-data-jpa#53]
https://spring.io/guides/gs/accessing-data-jpa/
https://github.com/spring-guides/gs-accessing-data-jpa

At above two place, please search "First, it fetches", and you can find the repeated text:
First, it fetches the CustomerRepository from the Spring application context. Then it saves a handful of Customer objects, demonstrating the save() method and setting up some data to use. Next, it calls findAll() to fetch all Customer objects from the database. Then it calls findOne() to fetch a single Customer by its ID. Finally, it calls findByLastName() to find all customers whose last name is "Bauer".

**Comment by Buzzardo** [comment]
Fixed
