### ISSUE TITLE
Code doesn't show in the "Accessing data with JPA" learning guide

### ISSUE THREAD

**Issue by mp911de** [spring-guides/gs-accessing-data-jpa#57]
Apologies if this is the wrong place to submit this docs issue, but i couldn't find any instructions on where and how to submit this issue on the spring.io site:
on the learning guide page: https://spring.io/guides/gs/accessing-data-jpa/
All the code errors out with the following:
```
Unresolved directive in - include::complete/pom.xml[]
Unresolved directive in - include::complete/src/main/java/com/example/accessingdatajpa/Customer.java[]
```
etc.

Originally reported at https://github.com/spring-projects/spring-data-jpa/issues/2142 by @nthali.

**Comment by Buzzardo** [comment]
The unresolved directives in the readme have been fixed.
