### ISSUE TITLE
Update Spring Boot to the latest version

### ISSUE THREAD

**Issue by robertmcnees** [spring-guides/gs-accessing-data-jpa#64]
Update the guide to use the most recent Spring Boot version.

Files that require changes are:

```
initial/build.gradle
initial/pom.xml
complete/build.gradle
complete/pom.xml
```

**Comment by 0scvr** [comment]
I'd like to work on this, please.

**Comment by robertmcnees** [comment]
No problem, @0scvr !  We don't assign issues in this repo but if you send a PR we will have a look.

**Comment by 0scvr** [comment]
Any reason my PR isn't getting merged ? Do I need to make some changes ?

**Comment by robertmcnees** [comment]
Thanks for the PR!  Looks good.  You even got the URL change to start.spring.io.  Bonus points for that one.
