### ISSUE TITLE
Update the Spring Boot version

### ISSUE THREAD

**Issue by Buzzardo** [spring-guides/gs-accessing-data-jpa#66]
An ongoing task is to keep the Spring Boot version current in the build files:

To do so, update the following files:

complete/build.gradle
complete/pom.xml
initial/build.gradle
initial/pom.xml

**Comment by GeorgePanaretos** [comment]
Resolved by https://github.com/spring-guides/gs-accessing-data-jpa/commit/f74c592c49b3c71727209cfc27fc2a8f61edb5eb

**Comment by Buzzardo** [comment]
Yes, it is. We leave one of these open all the time, though. As soon as the next patch release comes out, someone can fix this "issue" again. GitHub doesn't have an always-open issue mode.

**Comment by robertmcnees** [comment]
This project is now configured to use Dependabot.
